services:
  mongo1:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    volumes:
      - ./mongo1_data:/data/db
    ports:
      - 27017:27017
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]

  mongo2:
    image: mongo:6
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./mongo2_data:/data/db
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]

  mongo3:
    image: mongo:6
    hostname: mongo3
    container_name: mongo3
    volumes:
      - ./mongo3_data:/data/db
    ports:
      - 27019:27017
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
  mongosetup:
    image: mongo:6
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongo4_data:/data/db
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
